component: http
name: http-express-f3lJxRerJ
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    framework: express
    name: '${name}'
    runtime: Nodejs12.16
    eip: false
    timeout: 3
    memorySize: 512
    layers:
      - name: '${output:${stage}:${app}:my-first-server-less-application-layer.name}'
        version: >-
          ${output:${stage}:${app}:my-first-server-less-application-layer.version}
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-guangzhou
  isAutoCiDeploy: false
  static: {}
org: '1306483709'
app: my-first-server-less-application
stage: dev
